private_diary/diary/urls.py
from re import A
from django.urls import path

from . import views

app_name = 'diary'
urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),
  path('inquiry', views.InquiryView.as_view(), name='inquiry'),
  path('diary-list', views.DiaryListView.as_view(), name='diary_list'),
  path('diary-detail/<int:pk>/', views.DiaryDetailView.as_view(),name='diary_detail'),
  path('diary-create', views.DiaryCreateView.as_view(), name='diary_create'),
  path('diary-update/<int:pk>/', views.DiaryUpdateView.as_view(),name='diary_update'),
  path('diary-delete/<int:pk>/', views.DiaryDeleteView.as_view(), name='diary_delete'),
]

private_diary/private_diary/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
    # allauth has default routing
    path('accounts/', include('allauth.urls')),
]

# settings to deliver media on the local server
urlpatterns+=static(settings_common.MEDIA_URL, document_root =settings_dev.MEDIA_ROOT)

private_diary/accounts/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    """拡張ユーザーモデル"""

    class Meta:
        verbose_name_plural = 'CustomUser'

private_diary/diary/models.py
from accounts.models import CustomUser
from django.db import models


class Diary(models.Model):
    """diary model"""

    user = models.ForeignKey(CustomUser, on_delete=models.PROTECT)
    title = models.CharField(max_length=40)
    content = models.TextField(blank=True, null=True)
    photo1 = models.ImageField(blank=True, null=True)
    photo2 = models.ImageField(blank=True, null=True)
    photo3 = models.ImageField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

private_diary/diary/forms.py
from email import message
from django.core.mail import EmailMessage
from django import forms

from .models import Diary

# Not use model because no need to use database
class InquiryForm(forms.Form):
  name = forms.CharField(label='name', max_length=30)
  email = forms.EmailField(label='email')
  title = forms.CharField(label='title', max_length=30)
  message = forms.CharField(label='message', widget=forms.Textarea)

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)


  # default function
  def send_email(self):
    # get data from form
    name = self.cleaned_data['name']
    email = self.cleaned_data['email']
    title = self.cleaned_data['title']
    message = self.cleaned_data['message']

    # make each args of EmailMessage
    subject = 'お問い合わせ'
    message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name,email,message)
    from_email = 'yutounwasese@gmail.com'
    to_list = [
      'geek.yuto@gmail.com'
    ]
    cc_list = [
      email
    ]
    message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
    message.send()

# use model because use database this time
class DiaryCreateForm(forms.ModelForm):
    class Meta:
        model = Diary
        # fields = ('title', 'content', 'photo1', 'photo2', 'photo3',)
        fields = '__all__'

    # this is how to apply Bootstrap form-control class to all field
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

private_diary/accounts/views.py
from django.shortcuts import render

# Create your views here.

private_diary/diary/views.py
from audioop import reverse
from email.policy import default
import imp
from operator import ipow
from re import template
from django.views import generic
from django.contrib import messages
from django.urls import reverse_lazy
import logging
from .forms import InquiryForm, DiaryCreateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Diary
# logger setting
logger = logging.getLogger(__name__)

class IndexView(generic.TemplateView):
  template_name = "index.html"

class InquiryView(generic.FormView):
  template_name = "inquiry.html"
  form_class = InquiryForm
  success_url = reverse_lazy('diary:inquiry')

  # run unless validation blocks form objects
  def form_valid(self, form):
    form.send_email()
    messages.success(self.request, 'Successfullly, an email has been sent:D')
    logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
    # call parent class's form_valid and send response to success_url
    return super().form_valid(form)

class DiaryListView(generic.ListView, LoginRequiredMixin):
  model = Diary
  template_name = 'diary_list.html'
  pagenate_by = 2

  # override get_queryset to filter queryset
  def get_queryset(self):
    diaries = Diary.objects.filter(user=self.request.user).order_by('-created_at')
    return diaries

class DiaryDetailView(generic.DetailView, LoginRequiredMixin):
  model = Diary
  template_name = 'diary_detail.html'

class DiaryCreateView(generic.CreateView, LoginRequiredMixin):
  model = Diary
  template_name = 'diary_create.html'
  form_class = DiaryCreateForm
  success_url = reverse_lazy('diary:diary_list')
    
  # This method is called when valid form data has been posted.
  def form_valid(self,form):
    # Use function below if input valuse is not enough and store input values in variable
    diary = form.save(commit=False)
    # At this time, user object from request also must be included.
    diary.user = self.request.user
    # save diary in the database
    diary.save()
    messages.success(self.request, 'Successfully, you have posted new diary.')
    return super().form_valid(form)

  # This method is called when valid form data has failed to post.
  def form_invalid(self, form):
    messages.error(self.request, 'Unfortunately, you failed to post new diary.')
  
class DiaryUpdateView(generic.UpdateView, LoginRequiredMixin):
  model = Diary
  template_name = 'diary_update.html'
  form_class = DiaryCreateForm

  # use this function instead of the success_url when using dynamic url
  def get_success_url(self):
    return reverse_lazy('diary:diary_detail', kwargs={'pk': self.kwargs['pk']})

  def form_valid(self, form):
    messages.success(self.request, 'Successfully, you have updated the diary.')
    return super().form_valid(form)

  def form_invalid(self, form):
    messages.error(self.request, 'Unfortunately, you failed to update the diary.')
    return super().form_invalid(form)

class DiaryDeleteView(generic.DeleteView, LoginRequiredMixin):
  model = Diary
  template_name = 'diary_delete.html'
  success_url = reverse_lazy('diary:diary_list')

  def delete(self, request, *args, **kwargs):
    messages.success(self.request, 'Successfully, you have deleted the diary.')
    return super().delete(self, request, *args, **kwargs)

private_diary/diary/templates/base.html
{% load static %}

<html lang="ja">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet">

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
  </head>

  <body>
	<div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
          <div class="container">
            <a class="navbar-brand" href="{% url 'diary:index' %}">PRIVATE DIARY</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item {% block active_inquiry %}{% endblock %}">
                  <a class="nav-link" href="{% url 'diary:inquiry' %}">INQUIRY</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item {% block active_diary_list %}{% endblock %}">
                  <a class="nav-link" href="{% url 'diary:diary_list' %}">DIARY LIST</a>
                </li>
                {% endif %}
              </ul>
              <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                  </li>
                {% else %}
                  <li class="nav-item {% block active_signup %}{% endblock %}">
                      <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                  </li>
                  <li class="nav-item {% block active_login %}{% endblock %}">
                      <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
                  </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>

        {% block header%}{% endblock %}

        {% if messages %}
          <div class="container">
              <div class="row">
                  <div class="my-div-style w-100">
                      <ul class="messages" style="list-style: none;">
                          {% for message in messages %}
                          <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                              {{ message }}
                          </li>
                          {% endfor %}
                      </ul>
                  </div>
              </div>
          </div>
        {% endif %}

        {% block contents%}{% endblock %}

        <!-- Footer -->
        <footer class="py-5 bg-black">
          <div class="container">
            <p class="m-0 text-center text-white small">Copyright &copy; Private Diary 2019</p>
          </div>
          <!-- /.container -->
        </footer>

        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  	</div>
  </body>

</html>

private_diary/diary/templates/diary_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}create diary | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <!--set enctype to be able to upload files-->
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

private_diary/diary/templates/diary_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}delete diary | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST">
                {% csrf_token %}
                <p>Are you sure you want to delete this diary??</p>
                <button class="btn btn-primary mt-5" type="submit">DELETE</button>
                <a class="btn btn-secondary mt-5 ml-2" href="{% url 'diary:diary_detail' object.pk %}">CANCEL</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

private_diary/diary/templates/diary_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}diary detail | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}


{% block contents %}
<div class="container">
    <div class="my-div-style w-100">
        <div class="row">
            <div class="col-3">
                <strong>Title</strong>
            </div>
            <div class="col-9">
                <!--By contrast to diary_list, only a record exists so use 'object' instead-->
                {{ object.title }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>Content</strong>
            </div>
            <div class="col-9">
                {{ object.content|linebreaksbr }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>Image</strong>
            </div>
            <div class="col-3">
                {% if object.photo1 %}
                    <img src="{{ object.photo1.url }}" width="200" height="200"/>
                {% endif %}
            </div>
            <div class="col-3">
                {% if object.photo2 %}
                    <img src="{{ object.photo2.url }}" width="200" height="200"/>
                {% endif %}
            </div>
            <div class="col-3">
                {% if object.photo3 %}
                    <img src="{{ object.photo3.url }}" width="200" height="200"/>
                {% endif %}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>Created_at</strong>
            </div>
            <div class="col-9">
                {{ object.created_at }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>Updated_at</strong>
            </div>
            <div class="col-9">
                {{ object.updated_at }}
            </div>
        </div>

        <a class="btn btn-success mt-5 mb-3" href="{% url 'diary:diary_update' diary.pk %}">UPDATE</a>
        <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'diary:diary_delete' diary.pk %}">DELETE</a>
    </div>
</div>
{% endblock %}

private_diary/diary/templates/diary_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Diary list | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="clearfix">
                    <a class="btn btn-primary float-right" href="{% url 'diary:diary_create' %}">Create New Post</a>
                </div> 
                <!-- use xxx_list because multiple table records exist -->
                {% for diary in diary_list %}
                    <div class="post-preview">
                        <a href="{% url 'diary:diary_detail' diary.id %}">
                          <h2 class="post-title">
                            {{ diary.title }}
                          </h2>
                          <h3 class="post-subtitle">
                            {{ diary.content|truncatechars:20 }}
                          </h3>
                        </a>
                        <p class="post-meta">{{ diary.created_at }}</p>
                    </div>
                    <hr>
                {% empty %}
                    <p>Diary does not exist</p>
                {% endfor %}

                <!-- Pagenation -->
                {% if is_paginated %}
                    <ul class="pagination">
                        <!-- Link to previous page -->
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}

                        <!-- Diaplay page number -->
                        {% for page_num in page_obj.paginator.page_range %}
                            {% if page_obj.number == page_num %}
                                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                            {% endif %}
                        {% endfor %}

                        <!-- Link to next page -->
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

private_diary/diary/templates/diary_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Update Diary | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <!--set enctype to be able to upload files-->
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">UPDATE</button>
                <!--object can be sabstitute for model_name(diary)-->
                <a class="btn btn-secondary ml-2" href="{% url 'diary:diary_detail' object.pk %}">CANCEL</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

private_diary/diary/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Store your private Diary here | Private Diary{% endblock %}

{% block header%}
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">Private Diary</h1>
      <h2 class="masthead-subheading mb-0">your private diary service</h2>
      <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5">LOG IN</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block contents %}
<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'img/01.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Web Diary</h2>
          <p>A diary having CREATE/UPDATE/DELETE</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'img/02.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4">Save Your Diary</h2>
          <p>Keep your diary on the web</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'img/03.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Membership System</h2>
          <p>Membership web diary service</p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

private_diary/diary/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ | Private Diary{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}

                <!-- Display errors not associated with specific field -->
                {{ form.non_field_errors }}

                {% for field in form %}
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">
                            <!-- Display column name -->
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class="col-sm-8">
                            <!-- field to fill in info -->
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}